### ISSUE TITLE
Stop doesnt work on longer tracks

### ISSUE THREAD

**Issue by chrisetlo** [BlitzKraig/fvtt-SoundBoard#61]
I'm running foundry on the Forge.  I have lots of custom sounds I'm using in my "Curse of Strahd" campaign. All are save as .ogg files.  All tracks play well, but longer tracks do not respond to the "stop" button.  Shorter tracks do.

**Comment by Blacklands** [comment]
I have the same issue. Foundry is set up manually on a virtual cloud server (running Ubuntu, can give more info if needed).

**Comment by mkampus** [comment]
Same issue. Foundry hosted on digitalocean. Long tracks keep playing and stop doesn't do a thing.

**Comment by BlitzKraig** [comment]
Do the longer tracks stop when you ctrl+click the sound button?

**Comment by davidgoering** [comment]
Can confirm I have the same issue. 
Seems it doesn't matter whether you click "Stop" or Ctrl + Click the sound button, both cases result in the following error being logged:
`foundry.js:54449 Uncaught (in promise) DOMException: Failed to execute 'disconnect' on 'AudioNode': the given destination is not connected.
    at AudioContainer._unloadMediaNode (https://click-clack-chronicles.eu.forge-vtt.com/scripts/foundry.js:54449:21)
    at AudioContainer.stop (https://click-clack-chronicles.eu.forge-vtt.com/scripts/foundry.js:54417:10)
    at Sound.stop (https://click-clack-chronicles.eu.forge-vtt.com/scripts/foundry.js:54766:20)
    at https://assets.forge-vtt.com/bazaar/modules/SoundBoard/1.5.3/helpers/soundboardaudiohelper.js:226:23
    at Array.forEach (<anonymous>)
    at SBAudioHelper.stop (https://assets.forge-vtt.com/bazaar/modules/SoundBoard/1.5.3/helpers/soundboardaudiohelper.js:225:16)
    at Function.stopSound (https://assets.forge-vtt.com/bazaar/modules/SoundBoard/1.5.3/soundboard.js:471:32)
    at Function.playSoundOrStopLoop (https://assets.forge-vtt.com/bazaar/modules/SoundBoard/1.5.3/soundboard.js:169:18)
    at HTMLButtonElement.onclick (https://click-clack-chronicles.eu.forge-vtt.com/game:1:12)`

**Comment by Raravin-Keebs** [comment]
Sadly still an issue. Is what it is
